server:
  port: 9090

spring:
  application:
    name: koerber-pharma
  datasource:
    url: jdbc:h2:mem:pharmadb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      apache:
        coyote.http11: DEBUG